version: '3.8'

services:
  web:
    build: ./backend
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

volumes:
  pgdata:
